version: "3.8"
services:

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/app
    ports:
     - "8000:8000"
    working_dir: /app
    command: npm start

  db:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    environment: